/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import connection.Session;
import model.Colaboradores;
import java.awt.event.ActionEvent;

/**
 *
 * @author Victor
 */
public class ColaboradoresFormulario extends javax.swing.JFrame {

    /**
     * Atributo de armazenamento da classe Colaboradores
     */
    private Colaboradores infoColaborador;

    private Session session;

    /**
     * Creates new form ColaboradoresFormulario
     */
    public ColaboradoresFormulario(char oper) {
        this.infoColaborador = new Colaboradores();
        this.session = Session.getInstance();

        setOper(oper);
        initComponents();
    }

    /**
     * # Atributo de validação de ação no formulário - C = criar usuário; - A =
     * alterar usuário;
     */
    private char oper = 'C';

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_funcao_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        title = new javax.swing.JLabel();
        user_nome = new javax.swing.JTextField();
        user_nome_label = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        user_email_label = new javax.swing.JLabel();
        user_funcao_label = new javax.swing.JLabel();
        user_funcao_colaborador = new javax.swing.JRadioButton();
        user_funcao_gestor = new javax.swing.JRadioButton();
        user_funcao_adm = new javax.swing.JRadioButton();
        user_fone = new javax.swing.JTextField();
        user_fone_label = new javax.swing.JLabel();
        user_cpf = new javax.swing.JTextField();
        user_cpf_label = new javax.swing.JLabel();
        user_endereco = new javax.swing.JTextField();
        user_endereco_label = new javax.swing.JLabel();
        user_numHoras = new javax.swing.JTextField();
        user_numHoras_label = new javax.swing.JLabel();
        user_salario = new javax.swing.JTextField();
        user_salario_label = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        user_senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Cadastro de Usuários");

        user_nome.setText("Insira o nome do usuário");
        user_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nomeActionPerformed(evt);
            }
        });

        user_nome_label.setText("Nome");

        user_email.setText("Insira o email do usuário");
        user_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_emailActionPerformed(evt);
            }
        });

        user_email_label.setText("Email");

        user_funcao_label.setText("Tipo de Usuário");

        user_funcao_group.add(user_funcao_colaborador);
        user_funcao_colaborador.setText("Colaborador");
        user_funcao_colaborador.setToolTipText("");
        user_funcao_colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_colaboradorActionPerformed(evt);
            }
        });
        user_funcao_colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_colaboradorActionPerformed(evt);
            }
        });

        user_funcao_group.add(user_funcao_gestor);
        user_funcao_gestor.setText("Gestor");
        user_funcao_gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_gestorActionPerformed(evt);
            }
        });
        user_funcao_gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_gestorActionPerformed(evt);
            }
        });

        user_funcao_group.add(user_funcao_adm);
        user_funcao_adm.setText("Administrador");
        user_funcao_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_admActionPerformed(evt);
            }
        });
        user_funcao_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_admActionPerformed(evt);
            }
        });

        user_fone.setText("Insira o telefone do usuário");
        user_fone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_foneActionPerformed(evt);
            }
        });

        user_fone_label.setText("Telefone");

        user_cpf.setText("Insira o cpf do usuário");
        user_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_cpfActionPerformed(evt);
            }
        });

        user_cpf_label.setText("CPF");

        user_endereco.setText("Insira o endereço do usuário");
        user_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_enderecoActionPerformed(evt);
            }
        });

        user_endereco_label.setText("Endereço");

        user_numHoras.setText("Insira o tempo disponível");
        user_numHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_numHorasActionPerformed(evt);
            }
        });

        user_numHoras_label.setText("Número de Horas");

        user_salario.setText("Pretensão");
        user_salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_salarioActionPerformed(evt);
            }
        });

        user_salario_label.setText("Salário");

        btn_cancelar.setText("CANCELAR");

        btn_cadastrar.setText("CADASTRAR");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        user_senha.setText("jPasswordField1");
        user_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_senhaActionPerformed(evt);
            }
        });

        jLabel1.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)
                                                .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(user_nome_label)
                                                                        .addComponent(user_nome,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                200,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(user_email_label)
                                                                        .addComponent(user_email,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                200,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(user_fone_label)
                                                                                        .addComponent(user_fone,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                200,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(user_cpf,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                200,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(user_cpf_label)))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        layout.createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        user_senha,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        200,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(
                                                                                                        user_salario))
                                                                                .addGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(
                                                                                                                user_endereco_label)
                                                                                                        .addComponent(
                                                                                                                user_endereco,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                200,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(
                                                                                                                user_numHoras,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                200,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addComponent(
                                                                                                                user_numHoras_label)
                                                                                                        .addComponent(
                                                                                                                user_salario_label)))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(user_funcao_label)
                                                                        .addComponent(user_funcao_colaborador)
                                                                        .addComponent(user_funcao_gestor)
                                                                        .addComponent(user_funcao_adm))))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(title)
                                .addContainerGap(183, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(user_nome_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(user_nome, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(user_email_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(user_fone_label)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(user_fone,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(user_cpf_label)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(user_cpf,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(user_endereco_label)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(user_endereco,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(user_numHoras_label)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(user_numHoras,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(user_funcao_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(user_funcao_colaborador)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(user_funcao_gestor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(user_funcao_adm)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(user_salario_label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(user_senha, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(user_salario, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(61, Short.MAX_VALUE)));

        setSize(new java.awt.Dimension(717, 395));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_senhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_senhaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_senhaActionPerformed

    private void user_funcao_colaboradorActionPerformed(ActionEvent evt) {// GEN-FIRST:event_user_funcao_colaboradorActionPerformed
        if (this.infoColaborador.getFuncao() != "colaborador") {
            this.infoColaborador.setFuncao("colaborador");
        }
    }// GEN-LAST:event_user_funcao_colaboradorActionPerformed

    private void user_funcao_gestorActionPerformed(ActionEvent evt) {// GEN-FIRST:event_user_funcao_gestorActionPerformed
        if (this.infoColaborador.getFuncao() != "gestor") {
            this.infoColaborador.setFuncao("gestor");
        }
    }// GEN-LAST:event_user_funcao_gestorActionPerformed

    private void user_funcao_admActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_funcao_admActionPerformed
        if (this.infoColaborador.getFuncao() != "admin") {
            this.infoColaborador.setFuncao("admin");
        }
    }// GEN-LAST:event_user_funcao_admActionPerformed

    private void user_nomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_nomeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_nomeActionPerformed

    private void user_emailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_emailActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_emailActionPerformed

    private void user_foneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_foneActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_foneActionPerformed

    private void user_cpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_cpfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_cpfActionPerformed

    private void user_numHorasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_numHorasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_numHorasActionPerformed

    private void user_salarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_salarioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_salarioActionPerformed

    private void user_enderecoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_user_salarioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_user_salarioActionPerformed

    /**
     * Método de Definição de Operação do Formulário
     *
     * @param $oper
     */
    public void setOper(char $oper) {
        this.oper = $oper;
    }

    /**
     * Botão de Cadastro de Novos Usuários
     *
     * @param evt
     */
    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {
        /**
         * Registro do Nome do Colaborador
         */
        String nome = user_nome.getText();

        /**
         * Registro de Email do Colaborador
         */
        String email = user_email.getText();

        /**
         * Registro de Telefone do Colaborador
         */
        String fone = user_fone.getText();

        /**
         * Registro de CPF do Colaborador
         */
        String cpf = user_cpf.getText();

        /**
         * Registro de Endereço do Colaborador
         */
        String endereco = user_endereco.getText();

        /**
         * Registro de Endereço do Colaborador
         */
        char[] tempSenha = user_senha.getPassword();
        String senha = new String(tempSenha);

        /**
         * Registro do Número de Horas do Colaborador
         */
        int numHoras = Integer.parseInt(user_numHoras.getText());

        /**
         * Registro de Salário do Colaborador
         */
        Double salario = Double.valueOf(user_salario.getText());

        this.infoColaborador.setNome(nome);
        this.infoColaborador.setEmail(email);
        this.infoColaborador.setFone(fone);
        this.infoColaborador.setCpf(cpf);
        this.infoColaborador.setEndereco(endereco);
        this.infoColaborador.setSalario(salario);
        this.infoColaborador.setNumHoras(numHoras);

        this.infoColaborador.inserir(senha);

        System.out.println("CRIAR");
        System.out.println("new nome: " + nome);
        System.out.println("new salario: " + salario);
    }// GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * Botão de Atualização de Novos Usuários
     *
     * @param evt
     */
    private void btn_cadastrarAtualizarActionPerformed(java.awt.event.ActionEvent evt) {
        /**
         * Registro do Nome do Colaborador
         */
        String nome = user_nome.getText();

        /**
         * Registro de Email do Colaborador
         */
        String email = user_email.getText();

        /**
         * Registro de Telefone do Colaborador
         */
        String fone = user_fone.getText();

        /**
         * Registro de CPF do Colaborador
         */
        String cpf = user_cpf.getText();

        /**
         * Registro de Endereço do Colaborador
         */
        String endereco = user_endereco.getText();

        /**
         * Registro do Número de Horas do Colaborador
         */
        int numHoras = Integer.parseInt(user_numHoras.getText());

        /**
         * Registro de Salário do Colaborador
         */
        Double salario = Double.valueOf(user_salario.getText());

        Colaboradores p = new Colaboradores();
        p.setNome(nome);
        p.setEmail(email);
        p.setFone(fone);
        p.setCpf(cpf);
        p.setFuncao("teste");
        p.setEndereco(endereco);
        p.setSalario(salario);
        p.setNumHoras(numHoras);

        // p.atualizar("Teste@22");
        System.out.println("ATUALIZAR");
        System.out.println("new nome: " + nome);
        System.out.println("new salario: " + salario);
    }// GEN-LAST:event_btn_cadastrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel title;
    private javax.swing.JTextField user_cpf;
    private javax.swing.JLabel user_cpf_label;
    private javax.swing.JTextField user_email;
    private javax.swing.JLabel user_email_label;
    private javax.swing.JTextField user_endereco;
    private javax.swing.JLabel user_endereco_label;
    private javax.swing.JTextField user_fone;
    private javax.swing.JLabel user_fone_label;
    private javax.swing.JRadioButton user_funcao_adm;
    private javax.swing.JRadioButton user_funcao_colaborador;
    private javax.swing.JRadioButton user_funcao_gestor;
    private javax.swing.ButtonGroup user_funcao_group;
    private javax.swing.JLabel user_funcao_label;
    private javax.swing.JTextField user_nome;
    private javax.swing.JLabel user_nome_label;
    private javax.swing.JTextField user_numHoras;
    private javax.swing.JLabel user_numHoras_label;
    private javax.swing.JTextField user_salario;
    private javax.swing.JLabel user_salario_label;
    private javax.swing.JPasswordField user_senha;
    // End of variables declaration//GEN-END:variables
}
