/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controller;

import model.Equipes;

/**
 *
 * @author victo
 */
public class GestaoEquipes extends javax.swing.JFrame {

    /**
     * Atributo de armazenamento da classe Equipes
     */
    private Equipes infoEquipes;

    /**
     * Creates new form GestaoEquipes
     */
    public GestaoEquipes(char oper) {
        this.infoEquipes = new Equipes();

        setOper(oper);
        initComponents();
    }

    /**
     * # Atributo de validação de ação no formulário - C = criar; - A = alterar;
     */
    private char oper = 'C';

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        System.out.println("Operação Solicitada: " + this.oper);

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        telaFuncEquip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        infoIDs = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colabTable = new javax.swing.JTable();
        cadBtn = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Numero de funcionários:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        if (this.oper == 'C') {
            jLabel2.setText("Criação de Equipes");
        } else if (this.oper == 'A') {
            jLabel2.setText("Atualização de Equipes");
        }

        telaFuncEquip.setText("Insira a função da equipe");

        jLabel4.setText("Função da equipe");

        infoIDs.setText("Informar Códigos");
        infoIDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoIDsActionPerformed(evt);
            }
        });

        jLabel6.setText("Listagem de Funcionários disponíveis");

        colabTable.setModel(new javax.swing.table.DefaultTableModel(
                this.infoEquipes.getColabDisp(0),
                new String[] {
                        "Código", "Nome"
                }) {
            Class[] types = new Class[] {
                    java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(colabTable);
        if (colabTable.getColumnModel().getColumnCount() > 0) {
            colabTable.getColumnModel().getColumn(0).setResizable(false);
            colabTable.getColumnModel().getColumn(1).setResizable(false);
        }

        if (this.oper == 'A') {
            cadBtn.setText("ATUALIZAR");
            cadBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cadBtnAtualizarActionPerformed(evt);
                }
            });
        } else if (this.oper == 'C') {
            cadBtn.setText("CADASTRAR");
            cadBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cadBtnActionPerformed(evt);
                }
            });
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(464, 464, 464)
                                                .addComponent(jLabel5)
                                                .addGap(0, 47, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(telaFuncEquip)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jSpinner1)
                                                                        .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                240, Short.MAX_VALUE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(35, 35, 35)
                                                                .addComponent(infoIDs,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 189,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(99, 99, 99)
                                                .addComponent(jLabel2))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(214, 214, 214)
                                                .addComponent(cadBtn)))
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(telaFuncEquip, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(infoIDs)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36,
                                                        Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addGap(10, 10, 10))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cadBtn)
                                .addContainerGap(27, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadBtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadBtnAtualizarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cadBtnAtualizarActionPerformed

    private void cadBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_cadBtnActionPerformed

    private void infoIDsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_infoIDsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_infoIDsActionPerformed

    /**
     * Método de Definição de Operação do Formulário
     *
     * @param $oper
     */
    public void setOper(char $oper) {
        this.oper = $oper;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadBtn;
    private javax.swing.JTable colabTable;
    private javax.swing.JToggleButton infoIDs;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField telaFuncEquip;
    // End of variables declaration//GEN-END:variables
}
