/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev;

/**
 *
 * @author Victor
 */
public class ColaboradoresFormulario extends javax.swing.JFrame {

    /**
     * Creates new form ColaboradoresFormulario
     */
    public ColaboradoresFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_funcao_group = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        user_nome = new javax.swing.JTextField();
        user_nome_label = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        user_email_label = new javax.swing.JLabel();
        user_funcao_label = new javax.swing.JLabel();
        user_funcao_colaborador = new javax.swing.JRadioButton();
        user_funcao_gestor = new javax.swing.JRadioButton();
        user_funcao_adm = new javax.swing.JRadioButton();
        user_fone = new javax.swing.JTextField();
        user_fone_label = new javax.swing.JLabel();
        user_cpf = new javax.swing.JTextField();
        user_cpf_label = new javax.swing.JLabel();
        user_fone1 = new javax.swing.JTextField();
        user_fone_label1 = new javax.swing.JLabel();
        user_cpf1 = new javax.swing.JTextField();
        user_cpf_label1 = new javax.swing.JLabel();
        user_cpf2 = new javax.swing.JTextField();
        user_cpf_label2 = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        title.setText("Cadastro de Usuários");

        user_nome.setText("Insira o nome do usuário");
        user_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nomeActionPerformed(evt);
            }
        });

        user_nome_label.setText("Nome");

        user_email.setText("Insira o email do usuário");
        user_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_emailActionPerformed(evt);
            }
        });

        user_email_label.setText("Email");

        user_funcao_label.setText("Tipo de Usuário");

        user_funcao_group.add(user_funcao_colaborador);
        user_funcao_colaborador.setText("Colaborador");
        user_funcao_colaborador.setToolTipText("");
        user_funcao_colaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_colaboradorActionPerformed(evt);
            }
        });

        user_funcao_group.add(user_funcao_gestor);
        user_funcao_gestor.setText("Gestor");
        user_funcao_gestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_gestorActionPerformed(evt);
            }
        });

        user_funcao_group.add(user_funcao_adm);
        user_funcao_adm.setText("Administrador");
        user_funcao_adm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_funcao_admActionPerformed(evt);
            }
        });

        user_fone.setText("Insira o telefone do usuário");
        user_fone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_foneActionPerformed(evt);
            }
        });

        user_fone_label.setText("Telefone");

        user_cpf.setText("Insira o cpf do usuário");
        user_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_cpfActionPerformed(evt);
            }
        });

        user_cpf_label.setText("CPF");

        user_fone1.setText("Insira o endereço do usuário");
        user_fone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_fone1ActionPerformed(evt);
            }
        });

        user_fone_label1.setText("Endereço");

        user_cpf1.setText("Insira o tempo disponível");
        user_cpf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_cpf1ActionPerformed(evt);
            }
        });

        user_cpf_label1.setText("Número de Horas");

        user_cpf2.setText("R$ #.###,##");
        user_cpf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_cpf2ActionPerformed(evt);
            }
        });

        user_cpf_label2.setText("Salário");

        btn_cancelar.setText("CANCELAR");

        btn_cadastrar.setText("CADASTRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_nome_label)
                                    .addComponent(user_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_email_label)
                                    .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_funcao_label)
                                    .addComponent(user_funcao_colaborador)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_fone_label)
                                    .addComponent(user_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_cpf_label))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_funcao_gestor)
                                    .addComponent(user_funcao_adm)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_fone_label1)
                                    .addComponent(user_fone1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_cpf_label1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_cpf_label2)
                                    .addComponent(user_cpf2))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_funcao_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_funcao_colaborador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_nome_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_email_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_fone_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(user_cpf_label)
                            .addComponent(user_funcao_gestor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_funcao_adm))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_fone_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_fone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_cpf_label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_cpf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(user_cpf_label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(user_cpf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        user_fone_label.getAccessibleContext().setAccessibleName("Telefone");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nomeActionPerformed

    private void user_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_emailActionPerformed

    private void user_funcao_colaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_funcao_colaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_funcao_colaboradorActionPerformed

    private void user_funcao_gestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_funcao_gestorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_funcao_gestorActionPerformed

    private void user_funcao_admActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_funcao_admActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_funcao_admActionPerformed

    private void user_foneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_foneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_foneActionPerformed

    private void user_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_cpfActionPerformed

    private void user_fone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_fone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_fone1ActionPerformed

    private void user_cpf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_cpf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_cpf1ActionPerformed

    private void user_cpf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_cpf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_cpf2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColaboradoresFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColaboradoresFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColaboradoresFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColaboradoresFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColaboradoresFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel title;
    private javax.swing.JTextField user_cpf;
    private javax.swing.JTextField user_cpf1;
    private javax.swing.JTextField user_cpf2;
    private javax.swing.JLabel user_cpf_label;
    private javax.swing.JLabel user_cpf_label1;
    private javax.swing.JLabel user_cpf_label2;
    private javax.swing.JTextField user_email;
    private javax.swing.JLabel user_email_label;
    private javax.swing.JTextField user_fone;
    private javax.swing.JTextField user_fone1;
    private javax.swing.JLabel user_fone_label;
    private javax.swing.JLabel user_fone_label1;
    private javax.swing.JRadioButton user_funcao_adm;
    private javax.swing.JRadioButton user_funcao_colaborador;
    private javax.swing.JRadioButton user_funcao_gestor;
    private javax.swing.ButtonGroup user_funcao_group;
    private javax.swing.JLabel user_funcao_label;
    private javax.swing.JTextField user_nome;
    private javax.swing.JLabel user_nome_label;
    // End of variables declaration//GEN-END:variables
}
